// <auto-generated />
namespace Tailwind.Traders.Rewards.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "5.0.0")]
    public sealed partial class initial
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial));
        
        string Id
        {
            get { return "201811211722139_initial"; }
        }
        
        string Source
        {
            get { return null; }
        }
        
        string Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
